version: "2.4"

networks:

  frontend_net:
    driver: bridge

  backend_net:
    driver: bridge

services:

  app:
    image: app
    build:
      context: ./third-party
    environment:
      - PORT=8080
      - ATLAS_URI=mongodb://database
    networks:
      - frontend_net
      - backend_net
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mongo:6
    networks:
      - backend_net
    ports:
      - "27017:27017"
